cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

favorite/urls.py
# favorite/urls.py
from django.urls import path
from . import views

app_name = 'favorite'

urlpatterns = [
    path('product/<int:product_id>/add/', views.add_to_favorites, name='add_to_favorites'),
    path('product/<int:product_id>/remove/', views.remove_from_favorites, name='remove_from_favorites'),
    path('favorites/', views.favorite_list, name='favorite_list'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('favorite/', include('favorite.urls', namespace='favorite')),
    path('', include('shop.urls', namespace='shop')),
    
    

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [

    path('ayuda/', views.ayuda, name='ayuda'),

    path('quienes_somos/', views.quienes_somos, name='quienes_somos'),

    path('politica_privacidad/', views.politica_privacidad, name='politica_privacidad'),

    path('tyc/', views.tyc, name='tyc'),
    
    path('blog/', views.blog, name='blog'),


    path('', views.product_list, name='product_list'),
    path(
        '<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category'
    ),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail'
    ),
]

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse(
            'shop:product_list_by_category', args=[self.slug]
        )


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(
        upload_to='products/%Y/%m/%d',
        blank=True
    )
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import get_object_or_404, render

from cart.forms import CartAddProductForm
from .models import Category, Product
from django.http import HttpResponse



def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    cart_product_form = CartAddProductForm()  # Agregar el formulario aquí
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products,
            'cart_product_form': cart_product_form,  # Pasar el formulario al contexto
        },
    )


def product_detail(request, id, slug):
    product = get_object_or_404(
        Product, id=id, slug=slug, available=True
    )
    cart_product_form = CartAddProductForm()
    return render(
        request,
        'shop/product/detail.html',
        {'product': product, 'cart_product_form': cart_product_form},
    )

def ayuda(request):
    return render(request, 'info/ayuda.html')

def quienes_somos(request):
    return render(request, 'info/quienes_somos.html')

def politica_privacidad(request):
    return render(request, 'info/politica_privacidad.html')

def tyc(request):
    return render(request, 'info/terminos_condiciones.html')

def blog(request):
    return render(request, 'info/blog.html')



   

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}
{% block content %}
  <!-------------------------------------------------------------------------------------------------------------------->
<div>
  <button class="btn d-flex pm-0" onclick="history.back()">
    <img src="{% static 'img/iconos/atras.png' %}" alt="Volver" style="width: 40px; height: 40px; border: none;">
    
  </button>
</div>
  <div class="container mt-5">
  <div class="row" style="color: #4E50B4;">
    <div class="col">
      <h2 style="color: #4E50B4;"><strong>{{ product.name }}</strong></h2>
      <p class="price">Precio:  ${{ product.price }}</p>
      <p>{{ product.description|linebreaks }}</p>

      <form action="{% url "cart:cart_add" product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Agregar al carrito" class="mt-5" style="background-color: #4E50B4;">
      </form>
      {% if user.is_authenticated %}
      
      {% if is_favorite %}
        <form action="{% url 'favorite:remove_from_favorites' product.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Remove from Favorites">
        </form>
      {% else %}
        <form action="{% url 'favorite:add_to_favorites' product.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Add to Favorites" class="mt-5" style="background-color: #4E50B4;">
        </form>
      {% endif %}
    {% endif %}
    </div>
    <div class="col">
      <img src="{% if product.image %}{{ product.image.url }}{% else %}
      {% static "img/no_image.png" %}{% endif %}">
    </div>
  </div>
</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% if category %}{{ category.name }}{% else %}Productos{% endif %}
{% endblock %}

{% block content %}
<nav class="category-nav mb-3">
        <ul class="nav" style="background-color: #9394D5;">
            <li class="nav-item">
                <a class="nav-link {% if not category %}selected{% endif %}"
                    href="{% url 'shop:product_list' %}" style="color: #E7F1F6;">Todos los productos</a>
            </li>
            {% for c in categories %}
            <li class="nav-item">
                <a class="nav-link {% if category.slug == c.slug %}selected{% endif %}"
                    href="{{ c.get_absolute_url }}" style="color: #E7F1F6;">{{ c.name }}</a>
            </li>
            {% endfor %}
        </ul>
        
</nav>


<div id="" class="">
    <h2 class="text-center fw-bold" style="color: #4E50B4;">{% if category %}{{ category.name }}{% else %}Productos destacados{% endif %}</h2>
    
    <div class="container mt-5">
      <div class="row g-3">
          {% for product in products %}
          <div class="col-12 col-sm-6 col-md-4 col-lg-3">
              <div class="card product-card">
                  <a href="{{ product.get_absolute_url }}" class="d-flex justify-content-center">
                      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="card-img-top img-thumbnail" alt="{{ product.name }}">
                  </a>
                  <div class="card-body text-center">
                      <p class="card-title fw-medium">
                          <a href="{{ product.get_absolute_url }}" class="text-decoration-none" style="color: #4E50B4;">{{ product.name }}</a>
                      </p>
                      <p class="card-text fw-semibold" style="color: #4E50B4;">Precio:  ${{ product.price }}</p>
                      <form action="{% url 'cart:cart_add' product.id %}" method="post" class="me-">
                        {{ cart_product_form }}
                      <div class="d-flex justify-content-center align-items-center mt-3">
                          <!-- Formulario para agregar al carrito -->

                              {% csrf_token %}
                              <button class="btn m-2" style="background-color: #34DD78; border-radius: 50%; border: none;">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16" style="color: #4E50B4;">
                                      <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
                                  </svg> 
                              </button>
                          </form>
  
                          <!-- Formulario para agregar a favoritos -->
                          <form action="{% url 'favorite:add_to_favorites' product.id %}" method="post">
                              {% csrf_token %}
                              <button class="btn" style="background-color: #4E50B4; border-radius: 50%; border: none;">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16" style="color: #FFFFFF;">
                                      <path d="M8 3.314C12.438-1.248 23.534 4.735 8 15-7.534 4.736 3.562-1.248 8 3.314z"/>
                                  </svg>
                              </button>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
          {% endfor %}
      </div>
  </div>
  
  
</div>
<div id="" class="">
  <h2 class="text-center fw-bold" style="color: #4E50B4;">{% if category %}{{ category.name }}{% else %}Productos destacados{% endif %}</h2>


</div>
                <!--INFORMACION-->
<footer >
    <div class="container-fluid ">
      <div class="row">
        <div class="col-md-2 m-auto d-flex align-items-center">
          <img src="{%static 'img/logo_v_pharma.png'%}" alt="" width="100px">
        </div>

        <div class="col-md-3 p-5 " style="background-color: #a9a9dd;">
          <h3 style="color: white;">Contactos</h3>
          <a style="color: white;"><img src="{%static 'img/footer/whatsapp.png'%}" alt="logo_Whatsapp" width="30px">     +57 3126647917</a><br>
          <a href="" style="color: white; text-decoration: none;"><img src="{%static 'img/footer/gmail.png'%}" alt="" width="30px">   v-pharma@gmail.com</a>
        </div>

        <div class="col-md-3 p-5" style="background-color: #a9a9dd; ">
          <h3 style="color: white;">Siguenos</h3>
          <a href="" style="color: white; text-decoration: none;"><img src="{%static 'img/footer/instagram.png'%}" alt="logo_ig" width="30px">V-Pharma Oficial</a><br>
          <a href="" style="color: white; text-decoration: none;"><img src="{%static 'img/footer/facebook.png'%}" alt="logo_facebook" width="30px">V-Pharma</a>
        </div>
        <div class="col-md-4 p-5" style="background-color: #a9a9dd;">
          <div class="card" style="width: 18rem; background-color: #e7f1f6;">
            <div class="card-body">
              <p class="card-text">
                <a  href="{% url 'shop:ayuda'%}" style="color: #4e50b4; text-decoration: none;"><img src="{%static 'img/footer/ayuda.png'%}" alt="icon_help" width="20px">   Ayuda</a><br>
              </p>
              <p>
                <a href="{% url 'shop:quienes_somos'%}" style="color: #4e50b4; text-decoration: none;"><img src="{%static 'img/footer/quienes _somos.png'%}" alt="icon_quien_somos" width="20px">   Quienes somos</a><br>
              </p>
              <p>
                <a href="{% url 'shop:politica_privacidad' %}" style="color: #4e50b4;text-decoration: none;"><img src="{%static 'img/footer/politicas_privacidad.png'%}" alt=" icon_PdP" width="20px">   Politicas de Privacidad</a><br>
              </p>
              <p>
                <a href="{% url 'shop:tyc' %}" style="color: #4e50b4; text-decoration: none;"><img src="{%static 'img/footer/terminos-y-condiciones.png'%}" alt="icon_TyC" width="20px">   Terminos Y condiciones</a><br>
              </p>
              <p>
                <a href="{% url 'shop:blog' %}" style="color: #4e50b4; text-decoration: none;"><img src="{%static 'img/footer/blog.png'%}" alt="icon_blog" width="20px">   Blog</a><br>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
</footer>



{% endblock %}