cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

favorite/urls.py
# favorite/urls.py
from django.urls import path
from . import views

app_name = 'favorite'

urlpatterns = [
    path('product/<int:product_id>/add/', views.add_to_favorites, name='add_to_favorites'),
    path('product/<int:product_id>/remove/', views.remove_from_favorites, name='remove_from_favorites'),
    path('favorites/', views.favorite_list, name='favorite_list'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('favorite/', include('favorite.urls', namespace='favorite')),
    path('', include('shop.urls', namespace='shop')),
    
    

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [

    path('ayuda/', views.ayuda, name='ayuda'),

    path('quienes_somos/', views.quienes_somos, name='quienes_somos'),

    path('politica_privacidad/', views.politica_privacidad, name='politica_privacidad'),

    path('tyc/', views.tyc, name='tyc'),
    
    path('blog/', views.blog, name='blog'),


    path('', views.product_list, name='product_list'),
    path(
        '<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category'
    ),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail'
    ),
]

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse(
            'shop:product_list_by_category', args=[self.slug]
        )


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(
        upload_to='products/%Y/%m/%d',
        blank=True
    )
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import get_object_or_404, render

from cart.forms import CartAddProductForm
from .models import Category, Product
from django.http import HttpResponse



def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    cart_product_form = CartAddProductForm()  # Agregar el formulario aquí
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products,
            'cart_product_form': cart_product_form,  # Pasar el formulario al contexto
        },
    )


def product_detail(request, id, slug):
    product = get_object_or_404(
        Product, id=id, slug=slug, available=True
    )
    cart_product_form = CartAddProductForm()
    return render(
        request,
        'shop/product/detail.html',
        {'product': product, 'cart_product_form': cart_product_form},
    )

def ayuda(request):
    return render(request, 'info/ayuda.html')

def quienes_somos(request):
    return render(request, 'info/quienes_somos.html')

def politica_privacidad(request):
    return render(request, 'info/politica_privacidad.html')

def tyc(request):
    return render(request, 'info/terminos_condiciones.html')

def blog(request):
    return render(request, 'info/blog.html')



   

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}v-Pharma{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap');

    body {
      margin:0;
      padding:0;
      font-family: 'Poppins', sans-serif;
    }

    h1, h2, h3, h4, h5 , h6 {
      font-family: 'Poppins', sans-serif;
    }
    .navbar{
      margin: 0;
      padding: 0;
    }

    .product-card {
    max-width: 300px; /* Ajusta el ancho máximo de la tarjeta */
    margin: 1rem auto; /* Espaciado alrededor de la tarjeta y centrado automático */
    height: 400px; /* Altura fija de la tarjeta para mantener el diseño uniforme */
    display: flex;
    flex-direction: column;
  }

  .product-card img {
    height: 200px; /* Altura fija de la imagen para que todas las imágenes tengan la misma altura */
    object-fit: cover; /* Mantiene la proporción de la imagen y cubre el área especificada */
    border: none; /* Elimina el borde alrededor de la imagen */
    box-shadow: none; /* Elimina cualquier sombra alrededor de la imagen */
  }

  .card-body {
    flex: 1; /* Permite que el cuerpo de la tarjeta se expanda para llenar el espacio restante */
    display: flex;
    flex-direction: column;
    justify-content: center; /* Centra el contenido verticalmente */
    text-align: center;
    padding: 1rem; /* Espaciado dentro del cuerpo de la tarjeta */
  }

  .card-body p {
    margin-bottom: 0.5rem; /* Espaciado entre párrafos */
  }
    </style>
  </head>
  <body>
    <!-- NavBar -->
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid" style="background-color: #34DD78;">
          <a class="navbar-brand fw-bold me-5" href="#" style="color: #4E50B4; font-family: 'Poppins', sans-serif;">
            <img src={% static 'img/logo_v-pharma.jpg' %} alt="logo" width="50" class="me-1">
            V-Pharma
          </a>
          <form class="d-flex" role="search">
            <button class="btn me-2" type="submit" style="background-color: #4E50B4;">
              <img src={% static 'img/lupa.png' %} alt="logo" width="20">
            </button>
            <input class="form-control form" type="search" placeholder="¿Qué Buscas?" aria-label="Search">
          </form>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-disabled="true"></a>
              </li>
            </ul>
            <a class="me-5" href="{% url 'favorite:favorite_list' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="40"  fill="currentColor" class="bi bi-bookmark-star-fill" viewBox="0 0 16 16" style="color: #4E50B4;">
                <path fill-rule="evenodd" d="M2 15.5V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5M8.16 4.1a.178.178 0 0 0-.32 0l-.634 1.285a.18.18 0 0 1-.134.098l-1.42.206a.178.178 0 0 0-.098.303L6.58 6.993c.042.041.061.1.051.158L6.39 8.565a.178.178 0 0 0 .258.187l1.27-.668a.18.18 0 0 1 .165 0l1.27.668a.178.178 0 0 0 .257-.187L9.368 7.15a.18.18 0 0 1 .05-.158l1.028-1.001a.178.178 0 0 0-.098-.303l-1.42-.206a.18.18 0 0 1-.134-.098z"/>
              </svg>
            </a>
            <div class="d-flex align-items-center" style="position: relative; left: -20px;">
              <div>
                {% with total_items=cart|length %}
                  {% if total_items > 0 %}
                    <!-- Mostrar el ícono del carrito lleno si hay productos -->
                    <a href="{% url 'cart:cart_detail' %}" class="carrito">
                      <img id="icono-carrito" src="{% static 'img/carrito-lleno.png' %}" alt="Carrito lleno" width="50px"/>
                    </a>
                  {% else %}
                    <!-- Mostrar el ícono del carrito vacío si no hay productos -->
                    <a href="{% url 'cart:cart_detail' %}" class="carrito">
                      <img id="icono-carrito" src="{% static 'img/carrito-vacio.png' %}" alt="Carrito vacío" width="50px"/>
                    </a>
                  {% endif %}
                {% endwith %}
              </div>
            </div>
          </div>
        </div>
      </nav>
    <!-- NavBar -->


    <div id="row">
      {% block content %}
      {% endblock %}
    </div>

    <!-- base.html -->
{% if messages %}
<div class="messages">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
</div>
{% endif %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>